# default runner starts a GDB sesssion, which requires OpenOCD to be
# running, e.g.,
## openocd -f interface/stlink.cfg -f target/stm32f3x.cfg
# depending on your local GDB, pick one of the following
[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F303VCTx --log-format oneline  --connect-under-reset --speed 4000"
#runner = "probe-rs attach --chip STM32F303VCTx --log-format oneline"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x"
]


[build]
target = "thumbv7em-none-eabihf"

