[package]
edition = "2018"
name = "f3-sensor-hub"
version = "0.1.0"

[dependencies]
cortex-m = { version = "0.7.2", features = ["critical-section-single-core"]}
cortex-m-rt = "0.6.14"
#panic-itm = "0.4.2"
panic-probe = {version = "1.0.0", features = ["print-defmt"]}
defmt = "1.0.1"
defmt-rtt = "1.1.0"       # for RTT transport, optional if using ITM
defmt-itm = "0.4.0"       # for ITM transport

# HAL + board support
stm32f3-discovery = "0.7.2"
stm32f3xx-hal = { version = "0.7.0", features = ["stm32f303", "rt","stm32-usbd"] }
embedded-hal = "0.2"

# USB
usb-device = "0.2"
usbd-serial = "0.1"

heapless = "0.9.2"

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # !
incremental = false
lto = "fat"
opt-level = 'z' # !
overflow-checks = false

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 3
overflow-checks = false

[features]

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []