sensors:
  sensitivity:
    ACCELEROMETER: 0.0096138  # m/s^2 per bit
    GYROSCOPE: 0.00875        # m dps/LSB
    MAGNETOMETER: 1.5         # mGauss per bit
  sample_width:
    ACCELEROMETER: 12
    GYROSCOPE: 16
    MAGNETOMETER: 16

clock_freq_hz: 48000000

sample_encoding: BINARY
sample_animation: true

serial:
  baud_rate: 115200
  port_name: /dev/imu
